we use regularization to balance fit our data in our graph for more details  :   https://c3.ai/introduction-what-is-machine-learning/regularization/

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df=pd.read_csv('Melbourne_housing_FULL.csv')
df.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.8014,144.9958,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.7996,144.9984,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.8079,144.9934,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.8114,145.0116,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.8093,144.9944,Northern Metropolitan,4019.0

In [60]:
df.nunique()

Suburb             351
Address          34009
Rooms               12
Type                 3
Price             2871
Method               9
SellerG            388
Date                78
Distance           215
Postcode           211
Bedroom2            15
Bathroom            11
Car                 15
Landsize          1684
BuildingArea       740
YearBuilt          160
CouncilArea         33
Lattitude        13402
Longtitude       14524
Regionname           8
Propertycount      342
dtype: int64

In [61]:
df.isnull()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,False,False,False,False,False
34853,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34854,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34855,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,True,True,False,False
34856,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [63]:
obj_column=df.select_dtypes(include=['object'])

obj_column.head()

,Suburb,Address,Type,Method,SellerG,Date,CouncilArea,Regionname
0,Abbotsford,68 Studley St,h,SS,Jellis,3/09/2016,Yarra City Council,Northern Metropolitan
1,Abbotsford,85 Turner St,h,S,Biggin,3/12/2016,Yarra City Council,Northern Metropolitan
2,Abbotsford,25 Bloomburg St,h,S,Biggin,4/02/2016,Yarra City Council,Northern Metropolitan
3,Abbotsford,18/659 Victoria St,u,VB,Rounds,4/02/2016,Yarra City Council,Northern Metropolitan
4,Abbotsford,5 Charles St,h,SP,Biggin,4/03/2017,Yarra City Council,Northern Metropolitan

In [64]:
reduce_df=df.drop(['Address','Date','Postcode'],axis='columns')
reduce_df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,NaN,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [65]:
reduce_df.isnull()

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,False,False,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
34853,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34854,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
34855,False,False,False,False,False,False,False,True,True,True,True,True,True,False,True,True,False,False
34856,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [66]:
reduce_df.isna().sum()

Suburb               0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Distance             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

here we will fill some values with zero because this values are not missing they are not given because this valuse are mena to zero such as for bedroom , bathroom,cars the missing value indicates that there is no bedroom or bathroom for that flat

In [67]:
cols_to_zero=['Propertycount','Car','Bathroom','Bedroom2']
reduce_df[cols_to_zero]=reduce_df[cols_to_zero].fillna(0)
reduce_df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [68]:
fill_values = {}

for col in reduce_df.columns:
    if reduce_df[col].dtype == 'object':   # categorical/text columns
        fill_values[col] = reduce_df[col].mode()[0]
    else:                                  # numeric columns
        fill_values[col] = reduce_df[col].mean()

reduce_df = reduce_df.fillna(fill_values)
reduce_df

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,2,h,1.050173e+06,SS,Jellis,2.5,2.0,1.0,1.0,126.000000,160.2564,1965.289885,Yarra City Council,-37.801400,144.995800,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1.480000e+06,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,1965.289885,Yarra City Council,-37.799600,144.998400,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1.035000e+06,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,1900.000000,Yarra City Council,-37.807900,144.993400,Northern Metropolitan,4019.0
3,Abbotsford,3,u,1.050173e+06,VB,Rounds,2.5,3.0,2.0,1.0,0.000000,160.2564,1965.289885,Yarra City Council,-37.811400,145.011600,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1.465000e+06,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,1900.000000,Yarra City Council,-37.809300,144.994400,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1.480000e+06,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,1965.289885,Maribyrnong City Council,-37.810530,144.884670,Western Metropolitan,6543.0
34853,Yarraville,2,h,8.880000e+05,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,2018.000000,Maribyrnong City Council,-37.815510,144.888260,Western Metropolitan,6543.0
34854,Yarraville,2,t,7.050000e+05,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,2000.000000,Maribyrnong City Council,-37.822860,144.878560,Western Metropolitan,6543.0
34855,Yarraville,3,h,1.140000e+06,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,1965.289885,Maribyrnong City Council,-37.810634,145.001851,Western Metropolitan,6543.0
34856,Yarraville,2,h,1.020000e+06,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,1930.000000,Maribyrnong City Council,-37.818100,144.893510,Western Metropolitan,6543.0

In [69]:
reduce_df.isna().sum()

Suburb           0
Rooms            0
Type             0
Price            0
Method           0
SellerG          0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
YearBuilt        0
CouncilArea      0
Lattitude        0
Longtitude       0
Regionname       0
Propertycount    0
dtype: int64

In [70]:
dataset=pd.get_dummies(reduce_df,drop_first=True)
dataset

,Rooms,Price,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,2,1.050173e+06,2.5,2.0,1.0,1.0,126.000000,160.2564,1965.289885,-37.801400,...,False,True,False,False,True,False,False,False,False,False
1,2,1.480000e+06,2.5,2.0,1.0,1.0,202.000000,160.2564,1965.289885,-37.799600,...,False,True,False,False,True,False,False,False,False,False
2,2,1.035000e+06,2.5,2.0,1.0,0.0,156.000000,79.0000,1900.000000,-37.807900,...,False,True,False,False,True,False,False,False,False,False
3,3,1.050173e+06,2.5,3.0,2.0,1.0,0.000000,160.2564,1965.289885,-37.811400,...,False,True,False,False,True,False,False,False,False,False
4,3,1.465000e+06,2.5,3.0,2.0,0.0,134.000000,150.0000,1900.000000,-37.809300,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1.480000e+06,6.3,4.0,1.0,3.0,593.000000,160.2564,1965.289885,-37.810530,...,False,False,False,False,False,False,False,False,True,False
34853,2,8.880000e+05,6.3,2.0,2.0,1.0,98.000000,104.0000,2018.000000,-37.815510,...,False,False,False,False,False,False,False,False,True,False
34854,2,7.050000e+05,6.3,2.0,1.0,2.0,220.000000,120.0000,2000.000000,-37.822860,...,False,False,False,False,False,False,False,False,True,False
34855,3,1.140000e+06,6.3,0.0,0.0,0.0,593.598993,160.2564,1965.289885,-37.810634,...,False,False,False,False,False,False,False,False,True,False
34856,2,1.020000e+06,6.3,2.0,1.0,0.0,250.000000,103.0000,1930.000000,-37.818100,...,False,False,False,False,False,False,False,False,True,False

In [71]:
X=dataset.drop('Price',axis='columns')
Y=dataset['Price']
X

,Rooms,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,...,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council,Regionname_Eastern Victoria,Regionname_Northern Metropolitan,Regionname_Northern Victoria,Regionname_South-Eastern Metropolitan,Regionname_Southern Metropolitan,Regionname_Western Metropolitan,Regionname_Western Victoria
0,2,2.5,2.0,1.0,1.0,126.000000,160.2564,1965.289885,-37.801400,144.995800,...,False,True,False,False,True,False,False,False,False,False
1,2,2.5,2.0,1.0,1.0,202.000000,160.2564,1965.289885,-37.799600,144.998400,...,False,True,False,False,True,False,False,False,False,False
2,2,2.5,2.0,1.0,0.0,156.000000,79.0000,1900.000000,-37.807900,144.993400,...,False,True,False,False,True,False,False,False,False,False
3,3,2.5,3.0,2.0,1.0,0.000000,160.2564,1965.289885,-37.811400,145.011600,...,False,True,False,False,True,False,False,False,False,False
4,3,2.5,3.0,2.0,0.0,134.000000,150.0000,1900.000000,-37.809300,144.994400,...,False,True,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,6.3,4.0,1.0,3.0,593.000000,160.2564,1965.289885,-37.810530,144.884670,...,False,False,False,False,False,False,False,False,True,False
34853,2,6.3,2.0,2.0,1.0,98.000000,104.0000,2018.000000,-37.815510,144.888260,...,False,False,False,False,False,False,False,False,True,False
34854,2,6.3,2.0,1.0,2.0,220.000000,120.0000,2000.000000,-37.822860,144.878560,...,False,False,False,False,False,False,False,False,True,False
34855,3,6.3,0.0,0.0,0.0,593.598993,160.2564,1965.289885,-37.810634,145.001851,...,False,False,False,False,False,False,False,False,True,False
34856,2,6.3,2.0,1.0,0.0,250.000000,103.0000,1930.000000,-37.818100,144.893510,...,False,False,False,False,False,False,False,False,True,False

In [72]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=2)

In [74]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression().fit(x_train,y_train)
reg.score(x_test,y_test)

0.37919850397470145

In [75]:
from sklearn import linear_model

lesso_reg = linear_model.Lasso(alpha=50,max_iter=100,tol=0.1)
lesso_reg.fit(x_train,y_train)
lesso_reg.score(x_test,y_test)

c:\Users\adelz\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.021e+15, tolerance: 7.883e+14
  model = cd_fast.enet_coordinate_descent(

0.38293989382479343